### ISSUE TITLE
rm_covsum doesn't accept variables with class difftime

### ISSUE THREAD

**Issue by khueniken** [biostatsPMH/reportRmd#24]
Wondering if we could add the ability to treat difftime variables as a continuous measure? I often compute differences between two dates (e.g. length of hospital stay). Not an urgent issue as I can convert them to numeric, but it would be nice if rm_covsum didn't throw an error. 

Reproducible example:

library(reportRmd)

dt <- data.frame(id=1:3,
                 start_date = as.Date(c("2024-01-01","2024-01-02","2024-01-03")),
                 end_date = as.Date(c("2024-01-03","2024-01-05","2024-01-10")))

dt$total_time <- dt$end_date - dt$start_date

rm_covsum(data=dt, covs="total_time") # Error in round(summary(subdata[[cov]]), digits): non-numeric argument to mathematical function

**Comment by lisa-avery** [comment]
Variables with class difftime are now converted to numeric and will be summarised by rm_covsum
