### ISSUE TITLE
Dollar signs causing problems in HTML output

### ISSUE THREAD

**Issue by ghost** [biostatsPMH/reportRmd#3]
[test.csv](https://github.com/biostatsPMH/reportRmd/files/9162618/test.csv)
test <- read.csv(file='test.csv')
#' Can't get the income variable labels to look good
#' currently function rmds removes the first "$" so that that output isn't bolded, but then the first "$" is dropped....
rows_bold <- c(1,14,27)
bold_cells <- as.matrix(expand.grid(c(1,5,9),1:ncol(test)))
outTable(tab=test, 
         to_indent = c(2:4),
         rows_bold=rows_bold,
         bold_cells = bold_cells)

**Comment by lisa-avery** [comment]
implemented Tyler's fix, now working for on-screen (HTML) output

**Comment by lisa-avery** [comment]
Fixed with Tyler's solution
